### PR TITLE
PNPM upgrade

### PR DESCRIPTION
**Pull request by Necmttn**

### CODE REVIEW

**Comment by chen-rn** [comment]
Would you mind double checking that pnpm works with EAS build?

That was the main reason why I chose to go with Yarn instead of PNPM at the time of starting this template.

**Comment by Necmttn** [comment]
> EAS build

Will check in theory, it should work

**Comment by Necmttn** [comment]
Having issues with expo/router 😅 before it gets to EAS

**Comment by chen-rn** [comment]
oh darn! Expo-router shouldn't interfere with the package manager, should it?
I remember create-t3-turbo uses pnpm, and I just couldn't get it to work. I believe they ended up patching it but it had to do with react native and pnpm, not necessarily expo.

What are the main benefits of PNPM when hoisting is disabled?

**Comment by VidunderGunder** [comment]
I use `pnpm` in an almost identical stack (has to stay private, though) and it's running in production on TestFlight with no hiccups. Very strongly prefer `pnpm` myself even though it doesn't play nicely with Expo for several reasons, so I could take a jab at this if I get some time next weekend. @ me if someone wants to try and you face any specific issues.

**Comment by chen-rn** [comment]
Ah that's great to hear! what would you say are the main advantages/disadvantages of pnpm over yarn3 for a universal stack?

Also, does it deploy to vercel nicely as well?

**Comment by Necmttn** [comment]
Hey @VidunderGunder would you have time to pair on it ? I'm trying to setup with pnpm but kept getting errors, would love to see your setup

**Comment by VidunderGunder** [comment]
@chen-rn Haven't gone to web for prod yet, but that's one of my next priorities in that project. Considering swapping over to this if I can get all my nice-to-haves from that project into CUA.

Hadn't heard about [tamogui](https://github.com/tamagui/tamagui) before, so I'm excited to see how it compares to my current setup using [dripsy](https://www.dripsy.xyz/) + [moti](https://moti.fyi/) and before that [NativeWind](https://www.nativewind.dev/).

Here's a legacy and unpolished starter I made as my first jab at native development, if someone wants some inspo: [create-xp-app](https://github.com/VidunderGunder/create-xp-app)

@Necmttn Yeah, sure - that would be nice. Here's a [time slot I have open for tomorrow](https://www.worldtimebuddy.com/?qm=1&lid=3143244&h=3143244&date=2023-2-27&sln=11-17&hf=1), if that could work.

**Pull request closed without merging**
